---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.ru.prometheus-metering-operator
  resources:
  - prometheusmeterings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ru.prometheus-metering-operator
  resources:
  - prometheusmeterings/finalizers
  verbs:
  - update
- apiGroups:
  - apps.ru.prometheus-metering-operator
  resources:
  - prometheusmeterings/status
  verbs:
  - get
  - patch
  - update
